<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
    </head>
    <body>
        <script type="text/javascript">
            // async function show(){
            //     let num = await Math.random();
            //     console.log(num)
            //     return num
            //     /* 若函数有返回值，相当于Promise.resolve(num),
            //         若没有定义返回值，则相当于执行了Promise.resolve()*/
            // }
            // show().then((val)=>{
            //     console.log('show()执行完成,结果为'+val)
            // })

            /* 
                async-await 是建立在 promise机制之上的，并不能取代其地位
                
                async 用来表示函数是异步的，async函数返回值是一个promise对象，可以使用.then()来添加回调函数
                await 不能单独存在，需要放在async函数内部，await后面可以是任何形式的js表达式，
                      但其最主要的意图是为了等待Promise对象被resolve.
                      所以如果await后面跟的是Promise对象，会造成异步函数停止执行，并等待Promise的解决；
                      如果跟的是其他js表达式，则会立即执行
                      
                特性：
                    1、await后面代码会等await内部代码全部完成后再执行
            */

            // 例：await后跟Promise对象
            // function sleep(){
            //     return new Promise((resolve,reject)=>{
            //         setTimeout(()=>{
            //             resolve('sleep enough')
            //         },1000)
            //     })
            // }

            // function normal(){
            //     console.log('normal')
            // }

            // async function goSleep(){
            //     await normal()
            //     console.log('start sleep')

            //     let state = await sleep()
            //     console.log(state)
            //     console.log('stop sleep')
            // }

            // goSleep()
            // // normal    start sleep     1000> sleep enough      stop sleep


            /* // 例：三个请求，后一个请求的参数为前一个请求获取的数据
            function require(param){
                return new Promise((resolve,reject)=>{
                    setTimeout(()=>{
                        resolve(param)
                    },2000)
                })
            }
               
            async function startRequire(){
                let result1 = await require('00')
                console.log(result1)
                let result2 = await require(result1+'_11')
                console.log(result2)
                let result3 = await require(result2+'_22')
                console.log(result3)
            }
               
            startRequire()
            // 00
            // 00_11
            // 00_11_22 */


            /* // reject的处理
            function resleep(){
                return new Promise((resolve,reject)=>{
                    setTimeout(()=>{
                        reject('want to sleep')
                    },2000)
                })
            }
               
            async function sleepError(){
                // let a = await resleep()
                // console.log(a)
                // 直接这样会报错
                
                // await 命令后面的 Promise 对象，运行结果可能是 rejected，所以最好把 await 命令放在 try...catch 代码块中。
                
                try {
                    let result = await resleep(1000);
                    console.log(result);
                } catch (err) {
                    console.log(err);
                }
            }
            sleepError() */


            // await in for 循环
            // async function forDemo() {
            //     let arr = [0,1,2,3,4]
            //     for(let i=0;i<arr.length;i++){
            //         await console.log(arr[i])
            //     }
            // }
            // forDemo()

           /* async function async1() {
                console.log(1)
                
                const result = await async2();
                console.log(3)
                
                // 类似于
                // Promise.resolve(async2()).then(() => {
                //     console.log(3);
                // })
            }
            async function async2() {
                console.log(2);
            }
            Promise.resolve().then(() => {
                console.log(4)
            })
            setTimeout(() => {
                console.log(5)
            })
            async1();
            console.log(6);
            // 1    2   6   4   3   5
            
            // 首先输出1 2 6 ，本轮循环宏任务结束，执行Promise.resolve()输出4
            // 开始执行本轮循环宏任务中的微任务 输出3
            // 开始下一轮循环，输出5
            // setTimeout(fn, 0)在下一轮“事件循环”开始时执行，Promise.resolve()在本轮“事件循环”结束时执行，console.log('one')则是立即执行，因此最先输出。 */
            
            
            async function func() {
              console.log('async!');
              const num1 = await get();
              console.log(`num1_${num1}`);
              const num2 = await num1+ 100;
              console.log(`num2 _${num2}`);
              const num3 = await num2 + 100;
              console.log(`num3_${num3}`);
            }
            
           async function get(){
                console.log(10)
                return 200
            }
            setTimeout(()=>{
                console.log('ok')
            })
            
            Promise.resolve().then(()=>{
                console.log('promise')
            })
            
            func();
            console.log('run!');
            // async!  10  run  promise  num1_200 num2_300 num3_400  ok
            await是异步等待，等待的是一个promise，因此await后面应该写一个promise对象，如果不是promise对象，那么就会被转成一个立即resolve的promise。async函数被调用后就立即执行，但一遇到await就会返回，等到 异步操作执行完成，再执行函数体内后面的语句
            
            
        </script>
    </body>
</html>